// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: iaGC8N7icN64RQS5kdk5ev
// Component: j_vGL5KXs3
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_fire_spot.module.css"; // plasmic-import: iaGC8N7icN64RQS5kdk5ev/projectcss
import * as sty from "./PlasmicShawnsHomepage.module.css"; // plasmic-import: j_vGL5KXs3/css

export type PlasmicShawnsHomepage__VariantMembers = {};

export type PlasmicShawnsHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicShawnsHomepage__VariantsArgs;
export const PlasmicShawnsHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicShawnsHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicShawnsHomepage__ArgsType;
export const PlasmicShawnsHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicShawnsHomepage__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultShawnsHomepageProps {
  className?: string;
}

function PlasmicShawnsHomepage__RenderFunc(props: {
  variants: PlasmicShawnsHomepage__VariantsArgs;
  args: PlasmicShawnsHomepage__ArgsType;
  overrides: PlasmicShawnsHomepage__OverridesType;
  dataFetches?: PlasmicShawnsHomepage__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        />
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicShawnsHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicShawnsHomepage__VariantsArgs;
    args?: PlasmicShawnsHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicShawnsHomepage__Fetches;
  } & Omit<PlasmicShawnsHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicShawnsHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicShawnsHomepage__ArgProps,
      internalVariantPropNames: PlasmicShawnsHomepage__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicShawnsHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicShawnsHomepage";
  } else {
    func.displayName = `PlasmicShawnsHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicShawnsHomepage = Object.assign(
  // Top-level PlasmicShawnsHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicShawnsHomepage
    internalVariantProps: PlasmicShawnsHomepage__VariantProps,
    internalArgProps: PlasmicShawnsHomepage__ArgProps
  }
);

export default PlasmicShawnsHomepage;
/* prettier-ignore-end */
